// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: walcdc.proto

package ai.sapper.walcdc.common.model;

/**
 * Protobuf type {@code ai_sapper_walcdc_common_model.ChangeMessage}
 */
public  final class ChangeMessage extends
    com.google.protobuf.GeneratedMessage
    implements ChangeMessageOrBuilder {
  // Use ChangeMessage.newBuilder() to construct.
  private ChangeMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private ChangeMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final ChangeMessage defaultInstance;
  public static ChangeMessage getDefaultInstance() {
    return defaultInstance;
  }

  public ChangeMessage getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private ChangeMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            namespace_ = input.readBytes();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            txId_ = input.readBytes();
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            entity_ = input.readBytes();
            break;
          }
          case 34: {
            bitField0_ |= 0x00000008;
            type_ = input.readBytes();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000010;
            timestamp_ = input.readUInt64();
            break;
          }
          case 48: {
            int rawValue = input.readEnum();
            ai.sapper.walcdc.common.model.ChangeMessage.SourceType value = ai.sapper.walcdc.common.model.ChangeMessage.SourceType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(6, rawValue);
            } else {
              bitField0_ |= 0x00000020;
              sourceType_ = value;
            }
            break;
          }
          case 58: {
            bitField0_ |= 0x00000040;
            body_ = input.readBytes();
            break;
          }
          case 66: {
            bitField0_ |= 0x00000080;
            domain_ = input.readBytes();
            break;
          }
          case 74: {
            bitField0_ |= 0x00000100;
            entityName_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_ChangeMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_ChangeMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.sapper.walcdc.common.model.ChangeMessage.class, ai.sapper.walcdc.common.model.ChangeMessage.Builder.class);
  }

  public static com.google.protobuf.Parser<ChangeMessage> PARSER =
      new com.google.protobuf.AbstractParser<ChangeMessage>() {
    public ChangeMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChangeMessage(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<ChangeMessage> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf enum {@code ai_sapper_walcdc_common_model.ChangeMessage.SourceType}
   */
  public enum SourceType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>KUDU = 0;</code>
     */
    KUDU(0, 0),
    /**
     * <code>DEBEZIUM = 1;</code>
     */
    DEBEZIUM(1, 1),
    ;

    /**
     * <code>KUDU = 0;</code>
     */
    public static final int KUDU_VALUE = 0;
    /**
     * <code>DEBEZIUM = 1;</code>
     */
    public static final int DEBEZIUM_VALUE = 1;


    public final int getNumber() { return value; }

    public static SourceType valueOf(int value) {
      switch (value) {
        case 0: return KUDU;
        case 1: return DEBEZIUM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SourceType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SourceType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SourceType>() {
            public SourceType findValueByNumber(int number) {
              return SourceType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ai.sapper.walcdc.common.model.ChangeMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final SourceType[] VALUES = values();

    public static SourceType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private SourceType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ai_sapper_walcdc_common_model.ChangeMessage.SourceType)
  }

  private int bitField0_;
  // required string namespace = 1;
  public static final int NAMESPACE_FIELD_NUMBER = 1;
  private java.lang.Object namespace_;
  /**
   * <code>required string namespace = 1;</code>
   */
  public boolean hasNamespace() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string namespace = 1;</code>
   */
  public java.lang.String getNamespace() {
    java.lang.Object ref = namespace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        namespace_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string namespace = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNamespaceBytes() {
    java.lang.Object ref = namespace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      namespace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required string txId = 2;
  public static final int TXID_FIELD_NUMBER = 2;
  private java.lang.Object txId_;
  /**
   * <code>required string txId = 2;</code>
   */
  public boolean hasTxId() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required string txId = 2;</code>
   */
  public java.lang.String getTxId() {
    java.lang.Object ref = txId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        txId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string txId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTxIdBytes() {
    java.lang.Object ref = txId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      txId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required string entity = 3;
  public static final int ENTITY_FIELD_NUMBER = 3;
  private java.lang.Object entity_;
  /**
   * <code>required string entity = 3;</code>
   */
  public boolean hasEntity() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>required string entity = 3;</code>
   */
  public java.lang.String getEntity() {
    java.lang.Object ref = entity_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        entity_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string entity = 3;</code>
   */
  public com.google.protobuf.ByteString
      getEntityBytes() {
    java.lang.Object ref = entity_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entity_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required string type = 4;
  public static final int TYPE_FIELD_NUMBER = 4;
  private java.lang.Object type_;
  /**
   * <code>required string type = 4;</code>
   */
  public boolean hasType() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>required string type = 4;</code>
   */
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        type_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string type = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required uint64 timestamp = 5;
  public static final int TIMESTAMP_FIELD_NUMBER = 5;
  private long timestamp_;
  /**
   * <code>required uint64 timestamp = 5;</code>
   */
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>required uint64 timestamp = 5;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  // required .ai_sapper_walcdc_common_model.ChangeMessage.SourceType sourceType = 6;
  public static final int SOURCETYPE_FIELD_NUMBER = 6;
  private ai.sapper.walcdc.common.model.ChangeMessage.SourceType sourceType_;
  /**
   * <code>required .ai_sapper_walcdc_common_model.ChangeMessage.SourceType sourceType = 6;</code>
   */
  public boolean hasSourceType() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>required .ai_sapper_walcdc_common_model.ChangeMessage.SourceType sourceType = 6;</code>
   */
  public ai.sapper.walcdc.common.model.ChangeMessage.SourceType getSourceType() {
    return sourceType_;
  }

  // required bytes body = 7;
  public static final int BODY_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString body_;
  /**
   * <code>required bytes body = 7;</code>
   */
  public boolean hasBody() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>required bytes body = 7;</code>
   */
  public com.google.protobuf.ByteString getBody() {
    return body_;
  }

  // optional string domain = 8;
  public static final int DOMAIN_FIELD_NUMBER = 8;
  private java.lang.Object domain_;
  /**
   * <code>optional string domain = 8;</code>
   */
  public boolean hasDomain() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional string domain = 8;</code>
   */
  public java.lang.String getDomain() {
    java.lang.Object ref = domain_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        domain_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string domain = 8;</code>
   */
  public com.google.protobuf.ByteString
      getDomainBytes() {
    java.lang.Object ref = domain_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      domain_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string entityName = 9;
  public static final int ENTITYNAME_FIELD_NUMBER = 9;
  private java.lang.Object entityName_;
  /**
   * <code>optional string entityName = 9;</code>
   */
  public boolean hasEntityName() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional string entityName = 9;</code>
   */
  public java.lang.String getEntityName() {
    java.lang.Object ref = entityName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        entityName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string entityName = 9;</code>
   */
  public com.google.protobuf.ByteString
      getEntityNameBytes() {
    java.lang.Object ref = entityName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      entityName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    namespace_ = "";
    txId_ = "";
    entity_ = "";
    type_ = "";
    timestamp_ = 0L;
    sourceType_ = ai.sapper.walcdc.common.model.ChangeMessage.SourceType.KUDU;
    body_ = com.google.protobuf.ByteString.EMPTY;
    domain_ = "";
    entityName_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasNamespace()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasTxId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasEntity()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasTimestamp()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasSourceType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasBody()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getNamespaceBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getTxIdBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getEntityBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBytes(4, getTypeBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeUInt64(5, timestamp_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeEnum(6, sourceType_.getNumber());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeBytes(7, body_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeBytes(8, getDomainBytes());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeBytes(9, getEntityNameBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getNamespaceBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getTxIdBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getEntityBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, getTypeBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, timestamp_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, sourceType_.getNumber());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, body_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, getDomainBytes());
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, getEntityNameBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static ai.sapper.walcdc.common.model.ChangeMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sapper.walcdc.common.model.ChangeMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.ChangeMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sapper.walcdc.common.model.ChangeMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.ChangeMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ai.sapper.walcdc.common.model.ChangeMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.ChangeMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static ai.sapper.walcdc.common.model.ChangeMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.ChangeMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ai.sapper.walcdc.common.model.ChangeMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(ai.sapper.walcdc.common.model.ChangeMessage prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ai_sapper_walcdc_common_model.ChangeMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements ai.sapper.walcdc.common.model.ChangeMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_ChangeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_ChangeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.sapper.walcdc.common.model.ChangeMessage.class, ai.sapper.walcdc.common.model.ChangeMessage.Builder.class);
    }

    // Construct using ai.sapper.walcdc.common.model.ChangeMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      namespace_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      txId_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      entity_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      type_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      timestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000010);
      sourceType_ = ai.sapper.walcdc.common.model.ChangeMessage.SourceType.KUDU;
      bitField0_ = (bitField0_ & ~0x00000020);
      body_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      domain_ = "";
      bitField0_ = (bitField0_ & ~0x00000080);
      entityName_ = "";
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_ChangeMessage_descriptor;
    }

    public ai.sapper.walcdc.common.model.ChangeMessage getDefaultInstanceForType() {
      return ai.sapper.walcdc.common.model.ChangeMessage.getDefaultInstance();
    }

    public ai.sapper.walcdc.common.model.ChangeMessage build() {
      ai.sapper.walcdc.common.model.ChangeMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ai.sapper.walcdc.common.model.ChangeMessage buildPartial() {
      ai.sapper.walcdc.common.model.ChangeMessage result = new ai.sapper.walcdc.common.model.ChangeMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.namespace_ = namespace_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.txId_ = txId_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.entity_ = entity_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.type_ = type_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.timestamp_ = timestamp_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.sourceType_ = sourceType_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.body_ = body_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.domain_ = domain_;
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000100;
      }
      result.entityName_ = entityName_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.sapper.walcdc.common.model.ChangeMessage) {
        return mergeFrom((ai.sapper.walcdc.common.model.ChangeMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.sapper.walcdc.common.model.ChangeMessage other) {
      if (other == ai.sapper.walcdc.common.model.ChangeMessage.getDefaultInstance()) return this;
      if (other.hasNamespace()) {
        bitField0_ |= 0x00000001;
        namespace_ = other.namespace_;
        onChanged();
      }
      if (other.hasTxId()) {
        bitField0_ |= 0x00000002;
        txId_ = other.txId_;
        onChanged();
      }
      if (other.hasEntity()) {
        bitField0_ |= 0x00000004;
        entity_ = other.entity_;
        onChanged();
      }
      if (other.hasType()) {
        bitField0_ |= 0x00000008;
        type_ = other.type_;
        onChanged();
      }
      if (other.hasTimestamp()) {
        setTimestamp(other.getTimestamp());
      }
      if (other.hasSourceType()) {
        setSourceType(other.getSourceType());
      }
      if (other.hasBody()) {
        setBody(other.getBody());
      }
      if (other.hasDomain()) {
        bitField0_ |= 0x00000080;
        domain_ = other.domain_;
        onChanged();
      }
      if (other.hasEntityName()) {
        bitField0_ |= 0x00000100;
        entityName_ = other.entityName_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasNamespace()) {
        
        return false;
      }
      if (!hasTxId()) {
        
        return false;
      }
      if (!hasEntity()) {
        
        return false;
      }
      if (!hasType()) {
        
        return false;
      }
      if (!hasTimestamp()) {
        
        return false;
      }
      if (!hasSourceType()) {
        
        return false;
      }
      if (!hasBody()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.sapper.walcdc.common.model.ChangeMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.sapper.walcdc.common.model.ChangeMessage) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required string namespace = 1;
    private java.lang.Object namespace_ = "";
    /**
     * <code>required string namespace = 1;</code>
     */
    public boolean hasNamespace() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string namespace = 1;</code>
     */
    public java.lang.String getNamespace() {
      java.lang.Object ref = namespace_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        namespace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string namespace = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      java.lang.Object ref = namespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string namespace = 1;</code>
     */
    public Builder setNamespace(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      namespace_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string namespace = 1;</code>
     */
    public Builder clearNamespace() {
      bitField0_ = (bitField0_ & ~0x00000001);
      namespace_ = getDefaultInstance().getNamespace();
      onChanged();
      return this;
    }
    /**
     * <code>required string namespace = 1;</code>
     */
    public Builder setNamespaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      namespace_ = value;
      onChanged();
      return this;
    }

    // required string txId = 2;
    private java.lang.Object txId_ = "";
    /**
     * <code>required string txId = 2;</code>
     */
    public boolean hasTxId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string txId = 2;</code>
     */
    public java.lang.String getTxId() {
      java.lang.Object ref = txId_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        txId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string txId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTxIdBytes() {
      java.lang.Object ref = txId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string txId = 2;</code>
     */
    public Builder setTxId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      txId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string txId = 2;</code>
     */
    public Builder clearTxId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      txId_ = getDefaultInstance().getTxId();
      onChanged();
      return this;
    }
    /**
     * <code>required string txId = 2;</code>
     */
    public Builder setTxIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      txId_ = value;
      onChanged();
      return this;
    }

    // required string entity = 3;
    private java.lang.Object entity_ = "";
    /**
     * <code>required string entity = 3;</code>
     */
    public boolean hasEntity() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string entity = 3;</code>
     */
    public java.lang.String getEntity() {
      java.lang.Object ref = entity_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        entity_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string entity = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEntityBytes() {
      java.lang.Object ref = entity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string entity = 3;</code>
     */
    public Builder setEntity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      entity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string entity = 3;</code>
     */
    public Builder clearEntity() {
      bitField0_ = (bitField0_ & ~0x00000004);
      entity_ = getDefaultInstance().getEntity();
      onChanged();
      return this;
    }
    /**
     * <code>required string entity = 3;</code>
     */
    public Builder setEntityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      entity_ = value;
      onChanged();
      return this;
    }

    // required string type = 4;
    private java.lang.Object type_ = "";
    /**
     * <code>required string type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string type = 4;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string type = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string type = 4;</code>
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string type = 4;</code>
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>required string type = 4;</code>
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      type_ = value;
      onChanged();
      return this;
    }

    // required uint64 timestamp = 5;
    private long timestamp_ ;
    /**
     * <code>required uint64 timestamp = 5;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint64 timestamp = 5;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>required uint64 timestamp = 5;</code>
     */
    public Builder setTimestamp(long value) {
      bitField0_ |= 0x00000010;
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required uint64 timestamp = 5;</code>
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000010);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    // required .ai_sapper_walcdc_common_model.ChangeMessage.SourceType sourceType = 6;
    private ai.sapper.walcdc.common.model.ChangeMessage.SourceType sourceType_ = ai.sapper.walcdc.common.model.ChangeMessage.SourceType.KUDU;
    /**
     * <code>required .ai_sapper_walcdc_common_model.ChangeMessage.SourceType sourceType = 6;</code>
     */
    public boolean hasSourceType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.ChangeMessage.SourceType sourceType = 6;</code>
     */
    public ai.sapper.walcdc.common.model.ChangeMessage.SourceType getSourceType() {
      return sourceType_;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.ChangeMessage.SourceType sourceType = 6;</code>
     */
    public Builder setSourceType(ai.sapper.walcdc.common.model.ChangeMessage.SourceType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      sourceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.ChangeMessage.SourceType sourceType = 6;</code>
     */
    public Builder clearSourceType() {
      bitField0_ = (bitField0_ & ~0x00000020);
      sourceType_ = ai.sapper.walcdc.common.model.ChangeMessage.SourceType.KUDU;
      onChanged();
      return this;
    }

    // required bytes body = 7;
    private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>required bytes body = 7;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required bytes body = 7;</code>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    /**
     * <code>required bytes body = 7;</code>
     */
    public Builder setBody(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bytes body = 7;</code>
     */
    public Builder clearBody() {
      bitField0_ = (bitField0_ & ~0x00000040);
      body_ = getDefaultInstance().getBody();
      onChanged();
      return this;
    }

    // optional string domain = 8;
    private java.lang.Object domain_ = "";
    /**
     * <code>optional string domain = 8;</code>
     */
    public boolean hasDomain() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string domain = 8;</code>
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        domain_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string domain = 8;</code>
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string domain = 8;</code>
     */
    public Builder setDomain(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      domain_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string domain = 8;</code>
     */
    public Builder clearDomain() {
      bitField0_ = (bitField0_ & ~0x00000080);
      domain_ = getDefaultInstance().getDomain();
      onChanged();
      return this;
    }
    /**
     * <code>optional string domain = 8;</code>
     */
    public Builder setDomainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      domain_ = value;
      onChanged();
      return this;
    }

    // optional string entityName = 9;
    private java.lang.Object entityName_ = "";
    /**
     * <code>optional string entityName = 9;</code>
     */
    public boolean hasEntityName() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string entityName = 9;</code>
     */
    public java.lang.String getEntityName() {
      java.lang.Object ref = entityName_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        entityName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string entityName = 9;</code>
     */
    public com.google.protobuf.ByteString
        getEntityNameBytes() {
      java.lang.Object ref = entityName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entityName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string entityName = 9;</code>
     */
    public Builder setEntityName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      entityName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string entityName = 9;</code>
     */
    public Builder clearEntityName() {
      bitField0_ = (bitField0_ & ~0x00000100);
      entityName_ = getDefaultInstance().getEntityName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string entityName = 9;</code>
     */
    public Builder setEntityNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
      entityName_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ai_sapper_walcdc_common_model.ChangeMessage)
  }

  static {
    defaultInstance = new ChangeMessage(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:ai_sapper_walcdc_common_model.ChangeMessage)
}

