// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: walcdc.proto

package ai.sapper.walcdc.common.model;

/**
 * Protobuf type {@code ai_sapper_walcdc_common_model.ChangeSet}
 */
public  final class ChangeSet extends
    com.google.protobuf.GeneratedMessage
    implements ChangeSetOrBuilder {
  // Use ChangeSet.newBuilder() to construct.
  private ChangeSet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private ChangeSet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final ChangeSet defaultInstance;
  public static ChangeSet getDefaultInstance() {
    return defaultInstance;
  }

  public ChangeSet getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private ChangeSet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            ai.sapper.walcdc.common.model.Transaction.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = tnx_.toBuilder();
            }
            tnx_ = input.readMessage(ai.sapper.walcdc.common.model.Transaction.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tnx_);
              tnx_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            ai.sapper.walcdc.common.model.Entity.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = entity_.toBuilder();
            }
            entity_ = input.readMessage(ai.sapper.walcdc.common.model.Entity.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(entity_);
              entity_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              changes_ = new java.util.ArrayList<ai.sapper.walcdc.common.model.DataFieldChange>();
              mutable_bitField0_ |= 0x00000004;
            }
            changes_.add(input.readMessage(ai.sapper.walcdc.common.model.DataFieldChange.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        changes_ = java.util.Collections.unmodifiableList(changes_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_ChangeSet_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_ChangeSet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.sapper.walcdc.common.model.ChangeSet.class, ai.sapper.walcdc.common.model.ChangeSet.Builder.class);
  }

  public static com.google.protobuf.Parser<ChangeSet> PARSER =
      new com.google.protobuf.AbstractParser<ChangeSet>() {
    public ChangeSet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChangeSet(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<ChangeSet> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required .ai_sapper_walcdc_common_model.Transaction tnx = 1;
  public static final int TNX_FIELD_NUMBER = 1;
  private ai.sapper.walcdc.common.model.Transaction tnx_;
  /**
   * <code>required .ai_sapper_walcdc_common_model.Transaction tnx = 1;</code>
   */
  public boolean hasTnx() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .ai_sapper_walcdc_common_model.Transaction tnx = 1;</code>
   */
  public ai.sapper.walcdc.common.model.Transaction getTnx() {
    return tnx_;
  }
  /**
   * <code>required .ai_sapper_walcdc_common_model.Transaction tnx = 1;</code>
   */
  public ai.sapper.walcdc.common.model.TransactionOrBuilder getTnxOrBuilder() {
    return tnx_;
  }

  // required .ai_sapper_walcdc_common_model.Entity entity = 2;
  public static final int ENTITY_FIELD_NUMBER = 2;
  private ai.sapper.walcdc.common.model.Entity entity_;
  /**
   * <code>required .ai_sapper_walcdc_common_model.Entity entity = 2;</code>
   */
  public boolean hasEntity() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required .ai_sapper_walcdc_common_model.Entity entity = 2;</code>
   */
  public ai.sapper.walcdc.common.model.Entity getEntity() {
    return entity_;
  }
  /**
   * <code>required .ai_sapper_walcdc_common_model.Entity entity = 2;</code>
   */
  public ai.sapper.walcdc.common.model.EntityOrBuilder getEntityOrBuilder() {
    return entity_;
  }

  // repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;
  public static final int CHANGES_FIELD_NUMBER = 3;
  private java.util.List<ai.sapper.walcdc.common.model.DataFieldChange> changes_;
  /**
   * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
   */
  public java.util.List<ai.sapper.walcdc.common.model.DataFieldChange> getChangesList() {
    return changes_;
  }
  /**
   * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
   */
  public java.util.List<? extends ai.sapper.walcdc.common.model.DataFieldChangeOrBuilder> 
      getChangesOrBuilderList() {
    return changes_;
  }
  /**
   * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
   */
  public int getChangesCount() {
    return changes_.size();
  }
  /**
   * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
   */
  public ai.sapper.walcdc.common.model.DataFieldChange getChanges(int index) {
    return changes_.get(index);
  }
  /**
   * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
   */
  public ai.sapper.walcdc.common.model.DataFieldChangeOrBuilder getChangesOrBuilder(
      int index) {
    return changes_.get(index);
  }

  private void initFields() {
    tnx_ = ai.sapper.walcdc.common.model.Transaction.getDefaultInstance();
    entity_ = ai.sapper.walcdc.common.model.Entity.getDefaultInstance();
    changes_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasTnx()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasEntity()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getTnx().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getEntity().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    for (int i = 0; i < getChangesCount(); i++) {
      if (!getChanges(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, tnx_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, entity_);
    }
    for (int i = 0; i < changes_.size(); i++) {
      output.writeMessage(3, changes_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, tnx_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, entity_);
    }
    for (int i = 0; i < changes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, changes_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static ai.sapper.walcdc.common.model.ChangeSet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sapper.walcdc.common.model.ChangeSet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.ChangeSet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sapper.walcdc.common.model.ChangeSet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.ChangeSet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ai.sapper.walcdc.common.model.ChangeSet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.ChangeSet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static ai.sapper.walcdc.common.model.ChangeSet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.ChangeSet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ai.sapper.walcdc.common.model.ChangeSet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(ai.sapper.walcdc.common.model.ChangeSet prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ai_sapper_walcdc_common_model.ChangeSet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements ai.sapper.walcdc.common.model.ChangeSetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_ChangeSet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_ChangeSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.sapper.walcdc.common.model.ChangeSet.class, ai.sapper.walcdc.common.model.ChangeSet.Builder.class);
    }

    // Construct using ai.sapper.walcdc.common.model.ChangeSet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getTnxFieldBuilder();
        getEntityFieldBuilder();
        getChangesFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (tnxBuilder_ == null) {
        tnx_ = ai.sapper.walcdc.common.model.Transaction.getDefaultInstance();
      } else {
        tnxBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (entityBuilder_ == null) {
        entity_ = ai.sapper.walcdc.common.model.Entity.getDefaultInstance();
      } else {
        entityBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (changesBuilder_ == null) {
        changes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        changesBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_ChangeSet_descriptor;
    }

    public ai.sapper.walcdc.common.model.ChangeSet getDefaultInstanceForType() {
      return ai.sapper.walcdc.common.model.ChangeSet.getDefaultInstance();
    }

    public ai.sapper.walcdc.common.model.ChangeSet build() {
      ai.sapper.walcdc.common.model.ChangeSet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ai.sapper.walcdc.common.model.ChangeSet buildPartial() {
      ai.sapper.walcdc.common.model.ChangeSet result = new ai.sapper.walcdc.common.model.ChangeSet(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (tnxBuilder_ == null) {
        result.tnx_ = tnx_;
      } else {
        result.tnx_ = tnxBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (entityBuilder_ == null) {
        result.entity_ = entity_;
      } else {
        result.entity_ = entityBuilder_.build();
      }
      if (changesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          changes_ = java.util.Collections.unmodifiableList(changes_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.changes_ = changes_;
      } else {
        result.changes_ = changesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.sapper.walcdc.common.model.ChangeSet) {
        return mergeFrom((ai.sapper.walcdc.common.model.ChangeSet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.sapper.walcdc.common.model.ChangeSet other) {
      if (other == ai.sapper.walcdc.common.model.ChangeSet.getDefaultInstance()) return this;
      if (other.hasTnx()) {
        mergeTnx(other.getTnx());
      }
      if (other.hasEntity()) {
        mergeEntity(other.getEntity());
      }
      if (changesBuilder_ == null) {
        if (!other.changes_.isEmpty()) {
          if (changes_.isEmpty()) {
            changes_ = other.changes_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureChangesIsMutable();
            changes_.addAll(other.changes_);
          }
          onChanged();
        }
      } else {
        if (!other.changes_.isEmpty()) {
          if (changesBuilder_.isEmpty()) {
            changesBuilder_.dispose();
            changesBuilder_ = null;
            changes_ = other.changes_;
            bitField0_ = (bitField0_ & ~0x00000004);
            changesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getChangesFieldBuilder() : null;
          } else {
            changesBuilder_.addAllMessages(other.changes_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasTnx()) {
        
        return false;
      }
      if (!hasEntity()) {
        
        return false;
      }
      if (!getTnx().isInitialized()) {
        
        return false;
      }
      if (!getEntity().isInitialized()) {
        
        return false;
      }
      for (int i = 0; i < getChangesCount(); i++) {
        if (!getChanges(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.sapper.walcdc.common.model.ChangeSet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.sapper.walcdc.common.model.ChangeSet) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required .ai_sapper_walcdc_common_model.Transaction tnx = 1;
    private ai.sapper.walcdc.common.model.Transaction tnx_ = ai.sapper.walcdc.common.model.Transaction.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        ai.sapper.walcdc.common.model.Transaction, ai.sapper.walcdc.common.model.Transaction.Builder, ai.sapper.walcdc.common.model.TransactionOrBuilder> tnxBuilder_;
    /**
     * <code>required .ai_sapper_walcdc_common_model.Transaction tnx = 1;</code>
     */
    public boolean hasTnx() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Transaction tnx = 1;</code>
     */
    public ai.sapper.walcdc.common.model.Transaction getTnx() {
      if (tnxBuilder_ == null) {
        return tnx_;
      } else {
        return tnxBuilder_.getMessage();
      }
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Transaction tnx = 1;</code>
     */
    public Builder setTnx(ai.sapper.walcdc.common.model.Transaction value) {
      if (tnxBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tnx_ = value;
        onChanged();
      } else {
        tnxBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Transaction tnx = 1;</code>
     */
    public Builder setTnx(
        ai.sapper.walcdc.common.model.Transaction.Builder builderForValue) {
      if (tnxBuilder_ == null) {
        tnx_ = builderForValue.build();
        onChanged();
      } else {
        tnxBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Transaction tnx = 1;</code>
     */
    public Builder mergeTnx(ai.sapper.walcdc.common.model.Transaction value) {
      if (tnxBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            tnx_ != ai.sapper.walcdc.common.model.Transaction.getDefaultInstance()) {
          tnx_ =
            ai.sapper.walcdc.common.model.Transaction.newBuilder(tnx_).mergeFrom(value).buildPartial();
        } else {
          tnx_ = value;
        }
        onChanged();
      } else {
        tnxBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Transaction tnx = 1;</code>
     */
    public Builder clearTnx() {
      if (tnxBuilder_ == null) {
        tnx_ = ai.sapper.walcdc.common.model.Transaction.getDefaultInstance();
        onChanged();
      } else {
        tnxBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Transaction tnx = 1;</code>
     */
    public ai.sapper.walcdc.common.model.Transaction.Builder getTnxBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTnxFieldBuilder().getBuilder();
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Transaction tnx = 1;</code>
     */
    public ai.sapper.walcdc.common.model.TransactionOrBuilder getTnxOrBuilder() {
      if (tnxBuilder_ != null) {
        return tnxBuilder_.getMessageOrBuilder();
      } else {
        return tnx_;
      }
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Transaction tnx = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        ai.sapper.walcdc.common.model.Transaction, ai.sapper.walcdc.common.model.Transaction.Builder, ai.sapper.walcdc.common.model.TransactionOrBuilder> 
        getTnxFieldBuilder() {
      if (tnxBuilder_ == null) {
        tnxBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            ai.sapper.walcdc.common.model.Transaction, ai.sapper.walcdc.common.model.Transaction.Builder, ai.sapper.walcdc.common.model.TransactionOrBuilder>(
                tnx_,
                getParentForChildren(),
                isClean());
        tnx_ = null;
      }
      return tnxBuilder_;
    }

    // required .ai_sapper_walcdc_common_model.Entity entity = 2;
    private ai.sapper.walcdc.common.model.Entity entity_ = ai.sapper.walcdc.common.model.Entity.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        ai.sapper.walcdc.common.model.Entity, ai.sapper.walcdc.common.model.Entity.Builder, ai.sapper.walcdc.common.model.EntityOrBuilder> entityBuilder_;
    /**
     * <code>required .ai_sapper_walcdc_common_model.Entity entity = 2;</code>
     */
    public boolean hasEntity() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Entity entity = 2;</code>
     */
    public ai.sapper.walcdc.common.model.Entity getEntity() {
      if (entityBuilder_ == null) {
        return entity_;
      } else {
        return entityBuilder_.getMessage();
      }
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Entity entity = 2;</code>
     */
    public Builder setEntity(ai.sapper.walcdc.common.model.Entity value) {
      if (entityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        entity_ = value;
        onChanged();
      } else {
        entityBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Entity entity = 2;</code>
     */
    public Builder setEntity(
        ai.sapper.walcdc.common.model.Entity.Builder builderForValue) {
      if (entityBuilder_ == null) {
        entity_ = builderForValue.build();
        onChanged();
      } else {
        entityBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Entity entity = 2;</code>
     */
    public Builder mergeEntity(ai.sapper.walcdc.common.model.Entity value) {
      if (entityBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            entity_ != ai.sapper.walcdc.common.model.Entity.getDefaultInstance()) {
          entity_ =
            ai.sapper.walcdc.common.model.Entity.newBuilder(entity_).mergeFrom(value).buildPartial();
        } else {
          entity_ = value;
        }
        onChanged();
      } else {
        entityBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Entity entity = 2;</code>
     */
    public Builder clearEntity() {
      if (entityBuilder_ == null) {
        entity_ = ai.sapper.walcdc.common.model.Entity.getDefaultInstance();
        onChanged();
      } else {
        entityBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Entity entity = 2;</code>
     */
    public ai.sapper.walcdc.common.model.Entity.Builder getEntityBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getEntityFieldBuilder().getBuilder();
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Entity entity = 2;</code>
     */
    public ai.sapper.walcdc.common.model.EntityOrBuilder getEntityOrBuilder() {
      if (entityBuilder_ != null) {
        return entityBuilder_.getMessageOrBuilder();
      } else {
        return entity_;
      }
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Entity entity = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        ai.sapper.walcdc.common.model.Entity, ai.sapper.walcdc.common.model.Entity.Builder, ai.sapper.walcdc.common.model.EntityOrBuilder> 
        getEntityFieldBuilder() {
      if (entityBuilder_ == null) {
        entityBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            ai.sapper.walcdc.common.model.Entity, ai.sapper.walcdc.common.model.Entity.Builder, ai.sapper.walcdc.common.model.EntityOrBuilder>(
                entity_,
                getParentForChildren(),
                isClean());
        entity_ = null;
      }
      return entityBuilder_;
    }

    // repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;
    private java.util.List<ai.sapper.walcdc.common.model.DataFieldChange> changes_ =
      java.util.Collections.emptyList();
    private void ensureChangesIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        changes_ = new java.util.ArrayList<ai.sapper.walcdc.common.model.DataFieldChange>(changes_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        ai.sapper.walcdc.common.model.DataFieldChange, ai.sapper.walcdc.common.model.DataFieldChange.Builder, ai.sapper.walcdc.common.model.DataFieldChangeOrBuilder> changesBuilder_;

    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public java.util.List<ai.sapper.walcdc.common.model.DataFieldChange> getChangesList() {
      if (changesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(changes_);
      } else {
        return changesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public int getChangesCount() {
      if (changesBuilder_ == null) {
        return changes_.size();
      } else {
        return changesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public ai.sapper.walcdc.common.model.DataFieldChange getChanges(int index) {
      if (changesBuilder_ == null) {
        return changes_.get(index);
      } else {
        return changesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public Builder setChanges(
        int index, ai.sapper.walcdc.common.model.DataFieldChange value) {
      if (changesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChangesIsMutable();
        changes_.set(index, value);
        onChanged();
      } else {
        changesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public Builder setChanges(
        int index, ai.sapper.walcdc.common.model.DataFieldChange.Builder builderForValue) {
      if (changesBuilder_ == null) {
        ensureChangesIsMutable();
        changes_.set(index, builderForValue.build());
        onChanged();
      } else {
        changesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public Builder addChanges(ai.sapper.walcdc.common.model.DataFieldChange value) {
      if (changesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChangesIsMutable();
        changes_.add(value);
        onChanged();
      } else {
        changesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public Builder addChanges(
        int index, ai.sapper.walcdc.common.model.DataFieldChange value) {
      if (changesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChangesIsMutable();
        changes_.add(index, value);
        onChanged();
      } else {
        changesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public Builder addChanges(
        ai.sapper.walcdc.common.model.DataFieldChange.Builder builderForValue) {
      if (changesBuilder_ == null) {
        ensureChangesIsMutable();
        changes_.add(builderForValue.build());
        onChanged();
      } else {
        changesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public Builder addChanges(
        int index, ai.sapper.walcdc.common.model.DataFieldChange.Builder builderForValue) {
      if (changesBuilder_ == null) {
        ensureChangesIsMutable();
        changes_.add(index, builderForValue.build());
        onChanged();
      } else {
        changesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public Builder addAllChanges(
        java.lang.Iterable<? extends ai.sapper.walcdc.common.model.DataFieldChange> values) {
      if (changesBuilder_ == null) {
        ensureChangesIsMutable();
        super.addAll(values, changes_);
        onChanged();
      } else {
        changesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public Builder clearChanges() {
      if (changesBuilder_ == null) {
        changes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        changesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public Builder removeChanges(int index) {
      if (changesBuilder_ == null) {
        ensureChangesIsMutable();
        changes_.remove(index);
        onChanged();
      } else {
        changesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public ai.sapper.walcdc.common.model.DataFieldChange.Builder getChangesBuilder(
        int index) {
      return getChangesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public ai.sapper.walcdc.common.model.DataFieldChangeOrBuilder getChangesOrBuilder(
        int index) {
      if (changesBuilder_ == null) {
        return changes_.get(index);  } else {
        return changesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public java.util.List<? extends ai.sapper.walcdc.common.model.DataFieldChangeOrBuilder> 
         getChangesOrBuilderList() {
      if (changesBuilder_ != null) {
        return changesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(changes_);
      }
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public ai.sapper.walcdc.common.model.DataFieldChange.Builder addChangesBuilder() {
      return getChangesFieldBuilder().addBuilder(
          ai.sapper.walcdc.common.model.DataFieldChange.getDefaultInstance());
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public ai.sapper.walcdc.common.model.DataFieldChange.Builder addChangesBuilder(
        int index) {
      return getChangesFieldBuilder().addBuilder(
          index, ai.sapper.walcdc.common.model.DataFieldChange.getDefaultInstance());
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange changes = 3;</code>
     */
    public java.util.List<ai.sapper.walcdc.common.model.DataFieldChange.Builder> 
         getChangesBuilderList() {
      return getChangesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        ai.sapper.walcdc.common.model.DataFieldChange, ai.sapper.walcdc.common.model.DataFieldChange.Builder, ai.sapper.walcdc.common.model.DataFieldChangeOrBuilder> 
        getChangesFieldBuilder() {
      if (changesBuilder_ == null) {
        changesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            ai.sapper.walcdc.common.model.DataFieldChange, ai.sapper.walcdc.common.model.DataFieldChange.Builder, ai.sapper.walcdc.common.model.DataFieldChangeOrBuilder>(
                changes_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        changes_ = null;
      }
      return changesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:ai_sapper_walcdc_common_model.ChangeSet)
  }

  static {
    defaultInstance = new ChangeSet(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:ai_sapper_walcdc_common_model.ChangeSet)
}

