// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: walcdc.proto

package ai.sapper.walcdc.common.model;

/**
 * Protobuf type {@code ai_sapper_walcdc_common_model.DataFieldChange}
 */
public  final class DataFieldChange extends
    com.google.protobuf.GeneratedMessage
    implements DataFieldChangeOrBuilder {
  // Use DataFieldChange.newBuilder() to construct.
  private DataFieldChange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private DataFieldChange(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final DataFieldChange defaultInstance;
  public static DataFieldChange getDefaultInstance() {
    return defaultInstance;
  }

  public DataFieldChange getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private DataFieldChange(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            ai.sapper.walcdc.common.model.FieldValue.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = value_.toBuilder();
            }
            value_ = input.readMessage(ai.sapper.walcdc.common.model.FieldValue.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(value_);
              value_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            ai.sapper.walcdc.common.model.DataFieldChange.ChangeOp value = ai.sapper.walcdc.common.model.DataFieldChange.ChangeOp.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(2, rawValue);
            } else {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                op_ = new java.util.ArrayList<ai.sapper.walcdc.common.model.DataFieldChange.ChangeOp>();
                mutable_bitField0_ |= 0x00000002;
              }
              op_.add(value);
            }
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              ai.sapper.walcdc.common.model.DataFieldChange.ChangeOp value = ai.sapper.walcdc.common.model.DataFieldChange.ChangeOp.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  op_ = new java.util.ArrayList<ai.sapper.walcdc.common.model.DataFieldChange.ChangeOp>();
                  mutable_bitField0_ |= 0x00000002;
                }
                op_.add(value);
              }
            }
            input.popLimit(oldLimit);
            break;
          }
          case 26: {
            ai.sapper.walcdc.common.model.FieldValue.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = original_.toBuilder();
            }
            original_ = input.readMessage(ai.sapper.walcdc.common.model.FieldValue.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(original_);
              original_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        op_ = java.util.Collections.unmodifiableList(op_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_DataFieldChange_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_DataFieldChange_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.sapper.walcdc.common.model.DataFieldChange.class, ai.sapper.walcdc.common.model.DataFieldChange.Builder.class);
  }

  public static com.google.protobuf.Parser<DataFieldChange> PARSER =
      new com.google.protobuf.AbstractParser<DataFieldChange>() {
    public DataFieldChange parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DataFieldChange(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<DataFieldChange> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf enum {@code ai_sapper_walcdc_common_model.DataFieldChange.ChangeOp}
   */
  public enum ChangeOp
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ADD = 0;</code>
     */
    ADD(0, 0),
    /**
     * <code>RENAME = 1;</code>
     */
    RENAME(1, 1),
    /**
     * <code>DROP = 2;</code>
     */
    DROP(2, 2),
    ;

    /**
     * <code>ADD = 0;</code>
     */
    public static final int ADD_VALUE = 0;
    /**
     * <code>RENAME = 1;</code>
     */
    public static final int RENAME_VALUE = 1;
    /**
     * <code>DROP = 2;</code>
     */
    public static final int DROP_VALUE = 2;


    public final int getNumber() { return value; }

    public static ChangeOp valueOf(int value) {
      switch (value) {
        case 0: return ADD;
        case 1: return RENAME;
        case 2: return DROP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChangeOp>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ChangeOp>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChangeOp>() {
            public ChangeOp findValueByNumber(int number) {
              return ChangeOp.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ai.sapper.walcdc.common.model.DataFieldChange.getDescriptor().getEnumTypes().get(0);
    }

    private static final ChangeOp[] VALUES = values();

    public static ChangeOp valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ChangeOp(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ai_sapper_walcdc_common_model.DataFieldChange.ChangeOp)
  }

  private int bitField0_;
  // required .ai_sapper_walcdc_common_model.FieldValue value = 1;
  public static final int VALUE_FIELD_NUMBER = 1;
  private ai.sapper.walcdc.common.model.FieldValue value_;
  /**
   * <code>required .ai_sapper_walcdc_common_model.FieldValue value = 1;</code>
   */
  public boolean hasValue() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .ai_sapper_walcdc_common_model.FieldValue value = 1;</code>
   */
  public ai.sapper.walcdc.common.model.FieldValue getValue() {
    return value_;
  }
  /**
   * <code>required .ai_sapper_walcdc_common_model.FieldValue value = 1;</code>
   */
  public ai.sapper.walcdc.common.model.FieldValueOrBuilder getValueOrBuilder() {
    return value_;
  }

  // repeated .ai_sapper_walcdc_common_model.DataFieldChange.ChangeOp op = 2;
  public static final int OP_FIELD_NUMBER = 2;
  private java.util.List<ai.sapper.walcdc.common.model.DataFieldChange.ChangeOp> op_;
  /**
   * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange.ChangeOp op = 2;</code>
   */
  public java.util.List<ai.sapper.walcdc.common.model.DataFieldChange.ChangeOp> getOpList() {
    return op_;
  }
  /**
   * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange.ChangeOp op = 2;</code>
   */
  public int getOpCount() {
    return op_.size();
  }
  /**
   * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange.ChangeOp op = 2;</code>
   */
  public ai.sapper.walcdc.common.model.DataFieldChange.ChangeOp getOp(int index) {
    return op_.get(index);
  }

  // optional .ai_sapper_walcdc_common_model.FieldValue original = 3;
  public static final int ORIGINAL_FIELD_NUMBER = 3;
  private ai.sapper.walcdc.common.model.FieldValue original_;
  /**
   * <code>optional .ai_sapper_walcdc_common_model.FieldValue original = 3;</code>
   */
  public boolean hasOriginal() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .ai_sapper_walcdc_common_model.FieldValue original = 3;</code>
   */
  public ai.sapper.walcdc.common.model.FieldValue getOriginal() {
    return original_;
  }
  /**
   * <code>optional .ai_sapper_walcdc_common_model.FieldValue original = 3;</code>
   */
  public ai.sapper.walcdc.common.model.FieldValueOrBuilder getOriginalOrBuilder() {
    return original_;
  }

  private void initFields() {
    value_ = ai.sapper.walcdc.common.model.FieldValue.getDefaultInstance();
    op_ = java.util.Collections.emptyList();
    original_ = ai.sapper.walcdc.common.model.FieldValue.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasValue()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getValue().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (hasOriginal()) {
      if (!getOriginal().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, value_);
    }
    for (int i = 0; i < op_.size(); i++) {
      output.writeEnum(2, op_.get(i).getNumber());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(3, original_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, value_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < op_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(op_.get(i).getNumber());
      }
      size += dataSize;
      size += 1 * op_.size();
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, original_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static ai.sapper.walcdc.common.model.DataFieldChange parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sapper.walcdc.common.model.DataFieldChange parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.DataFieldChange parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sapper.walcdc.common.model.DataFieldChange parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.DataFieldChange parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ai.sapper.walcdc.common.model.DataFieldChange parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.DataFieldChange parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static ai.sapper.walcdc.common.model.DataFieldChange parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.DataFieldChange parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ai.sapper.walcdc.common.model.DataFieldChange parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(ai.sapper.walcdc.common.model.DataFieldChange prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ai_sapper_walcdc_common_model.DataFieldChange}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements ai.sapper.walcdc.common.model.DataFieldChangeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_DataFieldChange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_DataFieldChange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.sapper.walcdc.common.model.DataFieldChange.class, ai.sapper.walcdc.common.model.DataFieldChange.Builder.class);
    }

    // Construct using ai.sapper.walcdc.common.model.DataFieldChange.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getValueFieldBuilder();
        getOriginalFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (valueBuilder_ == null) {
        value_ = ai.sapper.walcdc.common.model.FieldValue.getDefaultInstance();
      } else {
        valueBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      op_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      if (originalBuilder_ == null) {
        original_ = ai.sapper.walcdc.common.model.FieldValue.getDefaultInstance();
      } else {
        originalBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_DataFieldChange_descriptor;
    }

    public ai.sapper.walcdc.common.model.DataFieldChange getDefaultInstanceForType() {
      return ai.sapper.walcdc.common.model.DataFieldChange.getDefaultInstance();
    }

    public ai.sapper.walcdc.common.model.DataFieldChange build() {
      ai.sapper.walcdc.common.model.DataFieldChange result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ai.sapper.walcdc.common.model.DataFieldChange buildPartial() {
      ai.sapper.walcdc.common.model.DataFieldChange result = new ai.sapper.walcdc.common.model.DataFieldChange(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (valueBuilder_ == null) {
        result.value_ = value_;
      } else {
        result.value_ = valueBuilder_.build();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        op_ = java.util.Collections.unmodifiableList(op_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.op_ = op_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000002;
      }
      if (originalBuilder_ == null) {
        result.original_ = original_;
      } else {
        result.original_ = originalBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.sapper.walcdc.common.model.DataFieldChange) {
        return mergeFrom((ai.sapper.walcdc.common.model.DataFieldChange)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.sapper.walcdc.common.model.DataFieldChange other) {
      if (other == ai.sapper.walcdc.common.model.DataFieldChange.getDefaultInstance()) return this;
      if (other.hasValue()) {
        mergeValue(other.getValue());
      }
      if (!other.op_.isEmpty()) {
        if (op_.isEmpty()) {
          op_ = other.op_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureOpIsMutable();
          op_.addAll(other.op_);
        }
        onChanged();
      }
      if (other.hasOriginal()) {
        mergeOriginal(other.getOriginal());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasValue()) {
        
        return false;
      }
      if (!getValue().isInitialized()) {
        
        return false;
      }
      if (hasOriginal()) {
        if (!getOriginal().isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.sapper.walcdc.common.model.DataFieldChange parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.sapper.walcdc.common.model.DataFieldChange) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required .ai_sapper_walcdc_common_model.FieldValue value = 1;
    private ai.sapper.walcdc.common.model.FieldValue value_ = ai.sapper.walcdc.common.model.FieldValue.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        ai.sapper.walcdc.common.model.FieldValue, ai.sapper.walcdc.common.model.FieldValue.Builder, ai.sapper.walcdc.common.model.FieldValueOrBuilder> valueBuilder_;
    /**
     * <code>required .ai_sapper_walcdc_common_model.FieldValue value = 1;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.FieldValue value = 1;</code>
     */
    public ai.sapper.walcdc.common.model.FieldValue getValue() {
      if (valueBuilder_ == null) {
        return value_;
      } else {
        return valueBuilder_.getMessage();
      }
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.FieldValue value = 1;</code>
     */
    public Builder setValue(ai.sapper.walcdc.common.model.FieldValue value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        valueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.FieldValue value = 1;</code>
     */
    public Builder setValue(
        ai.sapper.walcdc.common.model.FieldValue.Builder builderForValue) {
      if (valueBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        valueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.FieldValue value = 1;</code>
     */
    public Builder mergeValue(ai.sapper.walcdc.common.model.FieldValue value) {
      if (valueBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            value_ != ai.sapper.walcdc.common.model.FieldValue.getDefaultInstance()) {
          value_ =
            ai.sapper.walcdc.common.model.FieldValue.newBuilder(value_).mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        valueBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.FieldValue value = 1;</code>
     */
    public Builder clearValue() {
      if (valueBuilder_ == null) {
        value_ = ai.sapper.walcdc.common.model.FieldValue.getDefaultInstance();
        onChanged();
      } else {
        valueBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.FieldValue value = 1;</code>
     */
    public ai.sapper.walcdc.common.model.FieldValue.Builder getValueBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getValueFieldBuilder().getBuilder();
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.FieldValue value = 1;</code>
     */
    public ai.sapper.walcdc.common.model.FieldValueOrBuilder getValueOrBuilder() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilder();
      } else {
        return value_;
      }
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.FieldValue value = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        ai.sapper.walcdc.common.model.FieldValue, ai.sapper.walcdc.common.model.FieldValue.Builder, ai.sapper.walcdc.common.model.FieldValueOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            ai.sapper.walcdc.common.model.FieldValue, ai.sapper.walcdc.common.model.FieldValue.Builder, ai.sapper.walcdc.common.model.FieldValueOrBuilder>(
                value_,
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }

    // repeated .ai_sapper_walcdc_common_model.DataFieldChange.ChangeOp op = 2;
    private java.util.List<ai.sapper.walcdc.common.model.DataFieldChange.ChangeOp> op_ =
      java.util.Collections.emptyList();
    private void ensureOpIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        op_ = new java.util.ArrayList<ai.sapper.walcdc.common.model.DataFieldChange.ChangeOp>(op_);
        bitField0_ |= 0x00000002;
      }
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange.ChangeOp op = 2;</code>
     */
    public java.util.List<ai.sapper.walcdc.common.model.DataFieldChange.ChangeOp> getOpList() {
      return java.util.Collections.unmodifiableList(op_);
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange.ChangeOp op = 2;</code>
     */
    public int getOpCount() {
      return op_.size();
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange.ChangeOp op = 2;</code>
     */
    public ai.sapper.walcdc.common.model.DataFieldChange.ChangeOp getOp(int index) {
      return op_.get(index);
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange.ChangeOp op = 2;</code>
     */
    public Builder setOp(
        int index, ai.sapper.walcdc.common.model.DataFieldChange.ChangeOp value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureOpIsMutable();
      op_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange.ChangeOp op = 2;</code>
     */
    public Builder addOp(ai.sapper.walcdc.common.model.DataFieldChange.ChangeOp value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureOpIsMutable();
      op_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange.ChangeOp op = 2;</code>
     */
    public Builder addAllOp(
        java.lang.Iterable<? extends ai.sapper.walcdc.common.model.DataFieldChange.ChangeOp> values) {
      ensureOpIsMutable();
      super.addAll(values, op_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .ai_sapper_walcdc_common_model.DataFieldChange.ChangeOp op = 2;</code>
     */
    public Builder clearOp() {
      op_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    // optional .ai_sapper_walcdc_common_model.FieldValue original = 3;
    private ai.sapper.walcdc.common.model.FieldValue original_ = ai.sapper.walcdc.common.model.FieldValue.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        ai.sapper.walcdc.common.model.FieldValue, ai.sapper.walcdc.common.model.FieldValue.Builder, ai.sapper.walcdc.common.model.FieldValueOrBuilder> originalBuilder_;
    /**
     * <code>optional .ai_sapper_walcdc_common_model.FieldValue original = 3;</code>
     */
    public boolean hasOriginal() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.FieldValue original = 3;</code>
     */
    public ai.sapper.walcdc.common.model.FieldValue getOriginal() {
      if (originalBuilder_ == null) {
        return original_;
      } else {
        return originalBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.FieldValue original = 3;</code>
     */
    public Builder setOriginal(ai.sapper.walcdc.common.model.FieldValue value) {
      if (originalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        original_ = value;
        onChanged();
      } else {
        originalBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.FieldValue original = 3;</code>
     */
    public Builder setOriginal(
        ai.sapper.walcdc.common.model.FieldValue.Builder builderForValue) {
      if (originalBuilder_ == null) {
        original_ = builderForValue.build();
        onChanged();
      } else {
        originalBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.FieldValue original = 3;</code>
     */
    public Builder mergeOriginal(ai.sapper.walcdc.common.model.FieldValue value) {
      if (originalBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004) &&
            original_ != ai.sapper.walcdc.common.model.FieldValue.getDefaultInstance()) {
          original_ =
            ai.sapper.walcdc.common.model.FieldValue.newBuilder(original_).mergeFrom(value).buildPartial();
        } else {
          original_ = value;
        }
        onChanged();
      } else {
        originalBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.FieldValue original = 3;</code>
     */
    public Builder clearOriginal() {
      if (originalBuilder_ == null) {
        original_ = ai.sapper.walcdc.common.model.FieldValue.getDefaultInstance();
        onChanged();
      } else {
        originalBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.FieldValue original = 3;</code>
     */
    public ai.sapper.walcdc.common.model.FieldValue.Builder getOriginalBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getOriginalFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.FieldValue original = 3;</code>
     */
    public ai.sapper.walcdc.common.model.FieldValueOrBuilder getOriginalOrBuilder() {
      if (originalBuilder_ != null) {
        return originalBuilder_.getMessageOrBuilder();
      } else {
        return original_;
      }
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.FieldValue original = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        ai.sapper.walcdc.common.model.FieldValue, ai.sapper.walcdc.common.model.FieldValue.Builder, ai.sapper.walcdc.common.model.FieldValueOrBuilder> 
        getOriginalFieldBuilder() {
      if (originalBuilder_ == null) {
        originalBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            ai.sapper.walcdc.common.model.FieldValue, ai.sapper.walcdc.common.model.FieldValue.Builder, ai.sapper.walcdc.common.model.FieldValueOrBuilder>(
                original_,
                getParentForChildren(),
                isClean());
        original_ = null;
      }
      return originalBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:ai_sapper_walcdc_common_model.DataFieldChange)
  }

  static {
    defaultInstance = new DataFieldChange(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:ai_sapper_walcdc_common_model.DataFieldChange)
}

