// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: walcdc.proto

package ai.sapper.walcdc.common.model;

public interface DDLChangeSetOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required .ai_sapper_walcdc_common_model.Transaction tnx = 1;
  /**
   * <code>required .ai_sapper_walcdc_common_model.Transaction tnx = 1;</code>
   */
  boolean hasTnx();
  /**
   * <code>required .ai_sapper_walcdc_common_model.Transaction tnx = 1;</code>
   */
  ai.sapper.walcdc.common.model.Transaction getTnx();
  /**
   * <code>required .ai_sapper_walcdc_common_model.Transaction tnx = 1;</code>
   */
  ai.sapper.walcdc.common.model.TransactionOrBuilder getTnxOrBuilder();

  // required .ai_sapper_walcdc_common_model.Entity entity = 2;
  /**
   * <code>required .ai_sapper_walcdc_common_model.Entity entity = 2;</code>
   */
  boolean hasEntity();
  /**
   * <code>required .ai_sapper_walcdc_common_model.Entity entity = 2;</code>
   */
  ai.sapper.walcdc.common.model.Entity getEntity();
  /**
   * <code>required .ai_sapper_walcdc_common_model.Entity entity = 2;</code>
   */
  ai.sapper.walcdc.common.model.EntityOrBuilder getEntityOrBuilder();

  // repeated .ai_sapper_walcdc_common_model.DDLFieldChange changes = 3;
  /**
   * <code>repeated .ai_sapper_walcdc_common_model.DDLFieldChange changes = 3;</code>
   */
  java.util.List<ai.sapper.walcdc.common.model.DDLFieldChange> 
      getChangesList();
  /**
   * <code>repeated .ai_sapper_walcdc_common_model.DDLFieldChange changes = 3;</code>
   */
  ai.sapper.walcdc.common.model.DDLFieldChange getChanges(int index);
  /**
   * <code>repeated .ai_sapper_walcdc_common_model.DDLFieldChange changes = 3;</code>
   */
  int getChangesCount();
  /**
   * <code>repeated .ai_sapper_walcdc_common_model.DDLFieldChange changes = 3;</code>
   */
  java.util.List<? extends ai.sapper.walcdc.common.model.DDLFieldChangeOrBuilder> 
      getChangesOrBuilderList();
  /**
   * <code>repeated .ai_sapper_walcdc_common_model.DDLFieldChange changes = 3;</code>
   */
  ai.sapper.walcdc.common.model.DDLFieldChangeOrBuilder getChangesOrBuilder(
      int index);
}
