// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: walcdc.proto

package ai.sapper.walcdc.common.model;

public interface DDLFieldChangeOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional .ai_sapper_walcdc_common_model.Field original = 1;
  /**
   * <code>optional .ai_sapper_walcdc_common_model.Field original = 1;</code>
   */
  boolean hasOriginal();
  /**
   * <code>optional .ai_sapper_walcdc_common_model.Field original = 1;</code>
   */
  ai.sapper.walcdc.common.model.Field getOriginal();
  /**
   * <code>optional .ai_sapper_walcdc_common_model.Field original = 1;</code>
   */
  ai.sapper.walcdc.common.model.FieldOrBuilder getOriginalOrBuilder();

  // optional .ai_sapper_walcdc_common_model.Field target = 2;
  /**
   * <code>optional .ai_sapper_walcdc_common_model.Field target = 2;</code>
   */
  boolean hasTarget();
  /**
   * <code>optional .ai_sapper_walcdc_common_model.Field target = 2;</code>
   */
  ai.sapper.walcdc.common.model.Field getTarget();
  /**
   * <code>optional .ai_sapper_walcdc_common_model.Field target = 2;</code>
   */
  ai.sapper.walcdc.common.model.FieldOrBuilder getTargetOrBuilder();
}
