// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: walcdc.proto

package ai.sapper.walcdc.common.model;

/**
 * Protobuf type {@code ai_sapper_walcdc_common_model.DDLFieldChange}
 */
public  final class DDLFieldChange extends
    com.google.protobuf.GeneratedMessage
    implements DDLFieldChangeOrBuilder {
  // Use DDLFieldChange.newBuilder() to construct.
  private DDLFieldChange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private DDLFieldChange(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final DDLFieldChange defaultInstance;
  public static DDLFieldChange getDefaultInstance() {
    return defaultInstance;
  }

  public DDLFieldChange getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private DDLFieldChange(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            ai.sapper.walcdc.common.model.Field.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = original_.toBuilder();
            }
            original_ = input.readMessage(ai.sapper.walcdc.common.model.Field.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(original_);
              original_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            ai.sapper.walcdc.common.model.Field.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              subBuilder = target_.toBuilder();
            }
            target_ = input.readMessage(ai.sapper.walcdc.common.model.Field.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(target_);
              target_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_DDLFieldChange_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_DDLFieldChange_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.sapper.walcdc.common.model.DDLFieldChange.class, ai.sapper.walcdc.common.model.DDLFieldChange.Builder.class);
  }

  public static com.google.protobuf.Parser<DDLFieldChange> PARSER =
      new com.google.protobuf.AbstractParser<DDLFieldChange>() {
    public DDLFieldChange parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DDLFieldChange(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<DDLFieldChange> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional .ai_sapper_walcdc_common_model.Field original = 1;
  public static final int ORIGINAL_FIELD_NUMBER = 1;
  private ai.sapper.walcdc.common.model.Field original_;
  /**
   * <code>optional .ai_sapper_walcdc_common_model.Field original = 1;</code>
   */
  public boolean hasOriginal() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional .ai_sapper_walcdc_common_model.Field original = 1;</code>
   */
  public ai.sapper.walcdc.common.model.Field getOriginal() {
    return original_;
  }
  /**
   * <code>optional .ai_sapper_walcdc_common_model.Field original = 1;</code>
   */
  public ai.sapper.walcdc.common.model.FieldOrBuilder getOriginalOrBuilder() {
    return original_;
  }

  // optional .ai_sapper_walcdc_common_model.Field target = 2;
  public static final int TARGET_FIELD_NUMBER = 2;
  private ai.sapper.walcdc.common.model.Field target_;
  /**
   * <code>optional .ai_sapper_walcdc_common_model.Field target = 2;</code>
   */
  public boolean hasTarget() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional .ai_sapper_walcdc_common_model.Field target = 2;</code>
   */
  public ai.sapper.walcdc.common.model.Field getTarget() {
    return target_;
  }
  /**
   * <code>optional .ai_sapper_walcdc_common_model.Field target = 2;</code>
   */
  public ai.sapper.walcdc.common.model.FieldOrBuilder getTargetOrBuilder() {
    return target_;
  }

  private void initFields() {
    original_ = ai.sapper.walcdc.common.model.Field.getDefaultInstance();
    target_ = ai.sapper.walcdc.common.model.Field.getDefaultInstance();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (hasOriginal()) {
      if (!getOriginal().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasTarget()) {
      if (!getTarget().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, original_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeMessage(2, target_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, original_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, target_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static ai.sapper.walcdc.common.model.DDLFieldChange parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sapper.walcdc.common.model.DDLFieldChange parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.DDLFieldChange parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sapper.walcdc.common.model.DDLFieldChange parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.DDLFieldChange parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ai.sapper.walcdc.common.model.DDLFieldChange parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.DDLFieldChange parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static ai.sapper.walcdc.common.model.DDLFieldChange parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.DDLFieldChange parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ai.sapper.walcdc.common.model.DDLFieldChange parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(ai.sapper.walcdc.common.model.DDLFieldChange prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ai_sapper_walcdc_common_model.DDLFieldChange}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements ai.sapper.walcdc.common.model.DDLFieldChangeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_DDLFieldChange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_DDLFieldChange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.sapper.walcdc.common.model.DDLFieldChange.class, ai.sapper.walcdc.common.model.DDLFieldChange.Builder.class);
    }

    // Construct using ai.sapper.walcdc.common.model.DDLFieldChange.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getOriginalFieldBuilder();
        getTargetFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (originalBuilder_ == null) {
        original_ = ai.sapper.walcdc.common.model.Field.getDefaultInstance();
      } else {
        originalBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (targetBuilder_ == null) {
        target_ = ai.sapper.walcdc.common.model.Field.getDefaultInstance();
      } else {
        targetBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_DDLFieldChange_descriptor;
    }

    public ai.sapper.walcdc.common.model.DDLFieldChange getDefaultInstanceForType() {
      return ai.sapper.walcdc.common.model.DDLFieldChange.getDefaultInstance();
    }

    public ai.sapper.walcdc.common.model.DDLFieldChange build() {
      ai.sapper.walcdc.common.model.DDLFieldChange result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ai.sapper.walcdc.common.model.DDLFieldChange buildPartial() {
      ai.sapper.walcdc.common.model.DDLFieldChange result = new ai.sapper.walcdc.common.model.DDLFieldChange(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (originalBuilder_ == null) {
        result.original_ = original_;
      } else {
        result.original_ = originalBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      if (targetBuilder_ == null) {
        result.target_ = target_;
      } else {
        result.target_ = targetBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.sapper.walcdc.common.model.DDLFieldChange) {
        return mergeFrom((ai.sapper.walcdc.common.model.DDLFieldChange)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.sapper.walcdc.common.model.DDLFieldChange other) {
      if (other == ai.sapper.walcdc.common.model.DDLFieldChange.getDefaultInstance()) return this;
      if (other.hasOriginal()) {
        mergeOriginal(other.getOriginal());
      }
      if (other.hasTarget()) {
        mergeTarget(other.getTarget());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (hasOriginal()) {
        if (!getOriginal().isInitialized()) {
          
          return false;
        }
      }
      if (hasTarget()) {
        if (!getTarget().isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.sapper.walcdc.common.model.DDLFieldChange parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.sapper.walcdc.common.model.DDLFieldChange) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional .ai_sapper_walcdc_common_model.Field original = 1;
    private ai.sapper.walcdc.common.model.Field original_ = ai.sapper.walcdc.common.model.Field.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        ai.sapper.walcdc.common.model.Field, ai.sapper.walcdc.common.model.Field.Builder, ai.sapper.walcdc.common.model.FieldOrBuilder> originalBuilder_;
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field original = 1;</code>
     */
    public boolean hasOriginal() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field original = 1;</code>
     */
    public ai.sapper.walcdc.common.model.Field getOriginal() {
      if (originalBuilder_ == null) {
        return original_;
      } else {
        return originalBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field original = 1;</code>
     */
    public Builder setOriginal(ai.sapper.walcdc.common.model.Field value) {
      if (originalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        original_ = value;
        onChanged();
      } else {
        originalBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field original = 1;</code>
     */
    public Builder setOriginal(
        ai.sapper.walcdc.common.model.Field.Builder builderForValue) {
      if (originalBuilder_ == null) {
        original_ = builderForValue.build();
        onChanged();
      } else {
        originalBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field original = 1;</code>
     */
    public Builder mergeOriginal(ai.sapper.walcdc.common.model.Field value) {
      if (originalBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            original_ != ai.sapper.walcdc.common.model.Field.getDefaultInstance()) {
          original_ =
            ai.sapper.walcdc.common.model.Field.newBuilder(original_).mergeFrom(value).buildPartial();
        } else {
          original_ = value;
        }
        onChanged();
      } else {
        originalBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field original = 1;</code>
     */
    public Builder clearOriginal() {
      if (originalBuilder_ == null) {
        original_ = ai.sapper.walcdc.common.model.Field.getDefaultInstance();
        onChanged();
      } else {
        originalBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field original = 1;</code>
     */
    public ai.sapper.walcdc.common.model.Field.Builder getOriginalBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getOriginalFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field original = 1;</code>
     */
    public ai.sapper.walcdc.common.model.FieldOrBuilder getOriginalOrBuilder() {
      if (originalBuilder_ != null) {
        return originalBuilder_.getMessageOrBuilder();
      } else {
        return original_;
      }
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field original = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        ai.sapper.walcdc.common.model.Field, ai.sapper.walcdc.common.model.Field.Builder, ai.sapper.walcdc.common.model.FieldOrBuilder> 
        getOriginalFieldBuilder() {
      if (originalBuilder_ == null) {
        originalBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            ai.sapper.walcdc.common.model.Field, ai.sapper.walcdc.common.model.Field.Builder, ai.sapper.walcdc.common.model.FieldOrBuilder>(
                original_,
                getParentForChildren(),
                isClean());
        original_ = null;
      }
      return originalBuilder_;
    }

    // optional .ai_sapper_walcdc_common_model.Field target = 2;
    private ai.sapper.walcdc.common.model.Field target_ = ai.sapper.walcdc.common.model.Field.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        ai.sapper.walcdc.common.model.Field, ai.sapper.walcdc.common.model.Field.Builder, ai.sapper.walcdc.common.model.FieldOrBuilder> targetBuilder_;
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field target = 2;</code>
     */
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field target = 2;</code>
     */
    public ai.sapper.walcdc.common.model.Field getTarget() {
      if (targetBuilder_ == null) {
        return target_;
      } else {
        return targetBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field target = 2;</code>
     */
    public Builder setTarget(ai.sapper.walcdc.common.model.Field value) {
      if (targetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        target_ = value;
        onChanged();
      } else {
        targetBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field target = 2;</code>
     */
    public Builder setTarget(
        ai.sapper.walcdc.common.model.Field.Builder builderForValue) {
      if (targetBuilder_ == null) {
        target_ = builderForValue.build();
        onChanged();
      } else {
        targetBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field target = 2;</code>
     */
    public Builder mergeTarget(ai.sapper.walcdc.common.model.Field value) {
      if (targetBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            target_ != ai.sapper.walcdc.common.model.Field.getDefaultInstance()) {
          target_ =
            ai.sapper.walcdc.common.model.Field.newBuilder(target_).mergeFrom(value).buildPartial();
        } else {
          target_ = value;
        }
        onChanged();
      } else {
        targetBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field target = 2;</code>
     */
    public Builder clearTarget() {
      if (targetBuilder_ == null) {
        target_ = ai.sapper.walcdc.common.model.Field.getDefaultInstance();
        onChanged();
      } else {
        targetBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field target = 2;</code>
     */
    public ai.sapper.walcdc.common.model.Field.Builder getTargetBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getTargetFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field target = 2;</code>
     */
    public ai.sapper.walcdc.common.model.FieldOrBuilder getTargetOrBuilder() {
      if (targetBuilder_ != null) {
        return targetBuilder_.getMessageOrBuilder();
      } else {
        return target_;
      }
    }
    /**
     * <code>optional .ai_sapper_walcdc_common_model.Field target = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        ai.sapper.walcdc.common.model.Field, ai.sapper.walcdc.common.model.Field.Builder, ai.sapper.walcdc.common.model.FieldOrBuilder> 
        getTargetFieldBuilder() {
      if (targetBuilder_ == null) {
        targetBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            ai.sapper.walcdc.common.model.Field, ai.sapper.walcdc.common.model.Field.Builder, ai.sapper.walcdc.common.model.FieldOrBuilder>(
                target_,
                getParentForChildren(),
                isClean());
        target_ = null;
      }
      return targetBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:ai_sapper_walcdc_common_model.DDLFieldChange)
  }

  static {
    defaultInstance = new DDLFieldChange(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:ai_sapper_walcdc_common_model.DDLFieldChange)
}

