// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: walcdc.proto

package ai.sapper.walcdc.common.model;

public interface EntityOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required string id = 1;
  /**
   * <code>required string id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>required string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>required string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  // required string namespace = 2;
  /**
   * <code>required string namespace = 2;</code>
   */
  boolean hasNamespace();
  /**
   * <code>required string namespace = 2;</code>
   */
  java.lang.String getNamespace();
  /**
   * <code>required string namespace = 2;</code>
   */
  com.google.protobuf.ByteString
      getNamespaceBytes();

  // required string name = 3;
  /**
   * <code>required string name = 3;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  // optional string schemaLocation = 4;
  /**
   * <code>optional string schemaLocation = 4;</code>
   */
  boolean hasSchemaLocation();
  /**
   * <code>optional string schemaLocation = 4;</code>
   */
  java.lang.String getSchemaLocation();
  /**
   * <code>optional string schemaLocation = 4;</code>
   */
  com.google.protobuf.ByteString
      getSchemaLocationBytes();
}
