// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: walcdc.proto

package ai.sapper.walcdc.common.model;

/**
 * Protobuf type {@code ai_sapper_walcdc_common_model.FieldValue}
 */
public  final class FieldValue extends
    com.google.protobuf.GeneratedMessage
    implements FieldValueOrBuilder {
  // Use FieldValue.newBuilder() to construct.
  private FieldValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private FieldValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final FieldValue defaultInstance;
  public static FieldValue getDefaultInstance() {
    return defaultInstance;
  }

  public FieldValue getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private FieldValue(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            ai.sapper.walcdc.common.model.Field.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
              subBuilder = field_.toBuilder();
            }
            field_ = input.readMessage(ai.sapper.walcdc.common.model.Field.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(field_);
              field_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            value_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_FieldValue_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_FieldValue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.sapper.walcdc.common.model.FieldValue.class, ai.sapper.walcdc.common.model.FieldValue.Builder.class);
  }

  public static com.google.protobuf.Parser<FieldValue> PARSER =
      new com.google.protobuf.AbstractParser<FieldValue>() {
    public FieldValue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FieldValue(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<FieldValue> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required .ai_sapper_walcdc_common_model.Field field = 1;
  public static final int FIELD_FIELD_NUMBER = 1;
  private ai.sapper.walcdc.common.model.Field field_;
  /**
   * <code>required .ai_sapper_walcdc_common_model.Field field = 1;</code>
   */
  public boolean hasField() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required .ai_sapper_walcdc_common_model.Field field = 1;</code>
   */
  public ai.sapper.walcdc.common.model.Field getField() {
    return field_;
  }
  /**
   * <code>required .ai_sapper_walcdc_common_model.Field field = 1;</code>
   */
  public ai.sapper.walcdc.common.model.FieldOrBuilder getFieldOrBuilder() {
    return field_;
  }

  // optional bytes value = 2;
  public static final int VALUE_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString value_;
  /**
   * <code>optional bytes value = 2;</code>
   */
  public boolean hasValue() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional bytes value = 2;</code>
   */
  public com.google.protobuf.ByteString getValue() {
    return value_;
  }

  private void initFields() {
    field_ = ai.sapper.walcdc.common.model.Field.getDefaultInstance();
    value_ = com.google.protobuf.ByteString.EMPTY;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasField()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getField().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeMessage(1, field_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, value_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, field_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, value_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static ai.sapper.walcdc.common.model.FieldValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sapper.walcdc.common.model.FieldValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.FieldValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sapper.walcdc.common.model.FieldValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.FieldValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ai.sapper.walcdc.common.model.FieldValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.FieldValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static ai.sapper.walcdc.common.model.FieldValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.FieldValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ai.sapper.walcdc.common.model.FieldValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(ai.sapper.walcdc.common.model.FieldValue prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ai_sapper_walcdc_common_model.FieldValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements ai.sapper.walcdc.common.model.FieldValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_FieldValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_FieldValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.sapper.walcdc.common.model.FieldValue.class, ai.sapper.walcdc.common.model.FieldValue.Builder.class);
    }

    // Construct using ai.sapper.walcdc.common.model.FieldValue.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getFieldFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (fieldBuilder_ == null) {
        field_ = ai.sapper.walcdc.common.model.Field.getDefaultInstance();
      } else {
        fieldBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      value_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_FieldValue_descriptor;
    }

    public ai.sapper.walcdc.common.model.FieldValue getDefaultInstanceForType() {
      return ai.sapper.walcdc.common.model.FieldValue.getDefaultInstance();
    }

    public ai.sapper.walcdc.common.model.FieldValue build() {
      ai.sapper.walcdc.common.model.FieldValue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ai.sapper.walcdc.common.model.FieldValue buildPartial() {
      ai.sapper.walcdc.common.model.FieldValue result = new ai.sapper.walcdc.common.model.FieldValue(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      if (fieldBuilder_ == null) {
        result.field_ = field_;
      } else {
        result.field_ = fieldBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.value_ = value_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.sapper.walcdc.common.model.FieldValue) {
        return mergeFrom((ai.sapper.walcdc.common.model.FieldValue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.sapper.walcdc.common.model.FieldValue other) {
      if (other == ai.sapper.walcdc.common.model.FieldValue.getDefaultInstance()) return this;
      if (other.hasField()) {
        mergeField(other.getField());
      }
      if (other.hasValue()) {
        setValue(other.getValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasField()) {
        
        return false;
      }
      if (!getField().isInitialized()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.sapper.walcdc.common.model.FieldValue parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.sapper.walcdc.common.model.FieldValue) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required .ai_sapper_walcdc_common_model.Field field = 1;
    private ai.sapper.walcdc.common.model.Field field_ = ai.sapper.walcdc.common.model.Field.getDefaultInstance();
    private com.google.protobuf.SingleFieldBuilder<
        ai.sapper.walcdc.common.model.Field, ai.sapper.walcdc.common.model.Field.Builder, ai.sapper.walcdc.common.model.FieldOrBuilder> fieldBuilder_;
    /**
     * <code>required .ai_sapper_walcdc_common_model.Field field = 1;</code>
     */
    public boolean hasField() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Field field = 1;</code>
     */
    public ai.sapper.walcdc.common.model.Field getField() {
      if (fieldBuilder_ == null) {
        return field_;
      } else {
        return fieldBuilder_.getMessage();
      }
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Field field = 1;</code>
     */
    public Builder setField(ai.sapper.walcdc.common.model.Field value) {
      if (fieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        field_ = value;
        onChanged();
      } else {
        fieldBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Field field = 1;</code>
     */
    public Builder setField(
        ai.sapper.walcdc.common.model.Field.Builder builderForValue) {
      if (fieldBuilder_ == null) {
        field_ = builderForValue.build();
        onChanged();
      } else {
        fieldBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Field field = 1;</code>
     */
    public Builder mergeField(ai.sapper.walcdc.common.model.Field value) {
      if (fieldBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001) &&
            field_ != ai.sapper.walcdc.common.model.Field.getDefaultInstance()) {
          field_ =
            ai.sapper.walcdc.common.model.Field.newBuilder(field_).mergeFrom(value).buildPartial();
        } else {
          field_ = value;
        }
        onChanged();
      } else {
        fieldBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Field field = 1;</code>
     */
    public Builder clearField() {
      if (fieldBuilder_ == null) {
        field_ = ai.sapper.walcdc.common.model.Field.getDefaultInstance();
        onChanged();
      } else {
        fieldBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Field field = 1;</code>
     */
    public ai.sapper.walcdc.common.model.Field.Builder getFieldBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getFieldFieldBuilder().getBuilder();
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Field field = 1;</code>
     */
    public ai.sapper.walcdc.common.model.FieldOrBuilder getFieldOrBuilder() {
      if (fieldBuilder_ != null) {
        return fieldBuilder_.getMessageOrBuilder();
      } else {
        return field_;
      }
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Field field = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        ai.sapper.walcdc.common.model.Field, ai.sapper.walcdc.common.model.Field.Builder, ai.sapper.walcdc.common.model.FieldOrBuilder> 
        getFieldFieldBuilder() {
      if (fieldBuilder_ == null) {
        fieldBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            ai.sapper.walcdc.common.model.Field, ai.sapper.walcdc.common.model.Field.Builder, ai.sapper.walcdc.common.model.FieldOrBuilder>(
                field_,
                getParentForChildren(),
                isClean());
        field_ = null;
      }
      return fieldBuilder_;
    }

    // optional bytes value = 2;
    private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes value = 2;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }
    /**
     * <code>optional bytes value = 2;</code>
     */
    public Builder setValue(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes value = 2;</code>
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      value_ = getDefaultInstance().getValue();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ai_sapper_walcdc_common_model.FieldValue)
  }

  static {
    defaultInstance = new FieldValue(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:ai_sapper_walcdc_common_model.FieldValue)
}

