// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: walcdc.proto

package ai.sapper.walcdc.common.model;

/**
 * Protobuf type {@code ai_sapper_walcdc_common_model.Field}
 */
public  final class Field extends
    com.google.protobuf.GeneratedMessage
    implements FieldOrBuilder {
  // Use Field.newBuilder() to construct.
  private Field(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Field(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Field defaultInstance;
  public static Field getDefaultInstance() {
    return defaultInstance;
  }

  public Field getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Field(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            name_ = input.readBytes();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();
            ai.sapper.walcdc.common.model.Field.DataType value = ai.sapper.walcdc.common.model.Field.DataType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(2, rawValue);
            } else {
              bitField0_ |= 0x00000002;
              dataType_ = value;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_Field_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_Field_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.sapper.walcdc.common.model.Field.class, ai.sapper.walcdc.common.model.Field.Builder.class);
  }

  public static com.google.protobuf.Parser<Field> PARSER =
      new com.google.protobuf.AbstractParser<Field>() {
    public Field parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Field(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Field> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf enum {@code ai_sapper_walcdc_common_model.Field.DataType}
   */
  public enum DataType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BOOLEAN = 0;</code>
     */
    BOOLEAN(0, 0),
    /**
     * <code>SHORT = 1;</code>
     */
    SHORT(1, 1),
    /**
     * <code>INT = 2;</code>
     */
    INT(2, 2),
    /**
     * <code>LONG = 3;</code>
     */
    LONG(3, 3),
    /**
     * <code>FLOAT = 4;</code>
     */
    FLOAT(4, 4),
    /**
     * <code>DOUBLE = 5;</code>
     */
    DOUBLE(5, 5),
    /**
     * <code>BYTE = 6;</code>
     */
    BYTE(6, 6),
    /**
     * <code>CHAR = 7;</code>
     */
    CHAR(7, 7),
    /**
     * <code>STRING = 8;</code>
     */
    STRING(8, 8),
    /**
     * <code>ARRAY = 9;</code>
     */
    ARRAY(9, 9),
    /**
     * <code>OBJECT = 10;</code>
     */
    OBJECT(10, 10),
    /**
     * <code>CUSTOM = 11;</code>
     */
    CUSTOM(11, 11),
    ;

    /**
     * <code>BOOLEAN = 0;</code>
     */
    public static final int BOOLEAN_VALUE = 0;
    /**
     * <code>SHORT = 1;</code>
     */
    public static final int SHORT_VALUE = 1;
    /**
     * <code>INT = 2;</code>
     */
    public static final int INT_VALUE = 2;
    /**
     * <code>LONG = 3;</code>
     */
    public static final int LONG_VALUE = 3;
    /**
     * <code>FLOAT = 4;</code>
     */
    public static final int FLOAT_VALUE = 4;
    /**
     * <code>DOUBLE = 5;</code>
     */
    public static final int DOUBLE_VALUE = 5;
    /**
     * <code>BYTE = 6;</code>
     */
    public static final int BYTE_VALUE = 6;
    /**
     * <code>CHAR = 7;</code>
     */
    public static final int CHAR_VALUE = 7;
    /**
     * <code>STRING = 8;</code>
     */
    public static final int STRING_VALUE = 8;
    /**
     * <code>ARRAY = 9;</code>
     */
    public static final int ARRAY_VALUE = 9;
    /**
     * <code>OBJECT = 10;</code>
     */
    public static final int OBJECT_VALUE = 10;
    /**
     * <code>CUSTOM = 11;</code>
     */
    public static final int CUSTOM_VALUE = 11;


    public final int getNumber() { return value; }

    public static DataType valueOf(int value) {
      switch (value) {
        case 0: return BOOLEAN;
        case 1: return SHORT;
        case 2: return INT;
        case 3: return LONG;
        case 4: return FLOAT;
        case 5: return DOUBLE;
        case 6: return BYTE;
        case 7: return CHAR;
        case 8: return STRING;
        case 9: return ARRAY;
        case 10: return OBJECT;
        case 11: return CUSTOM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
            public DataType findValueByNumber(int number) {
              return DataType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ai.sapper.walcdc.common.model.Field.getDescriptor().getEnumTypes().get(0);
    }

    private static final DataType[] VALUES = values();

    public static DataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private DataType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ai_sapper_walcdc_common_model.Field.DataType)
  }

  private int bitField0_;
  // required string name = 1;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.Object name_;
  /**
   * <code>required string name = 1;</code>
   */
  public boolean hasName() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        name_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required .ai_sapper_walcdc_common_model.Field.DataType dataType = 2;
  public static final int DATATYPE_FIELD_NUMBER = 2;
  private ai.sapper.walcdc.common.model.Field.DataType dataType_;
  /**
   * <code>required .ai_sapper_walcdc_common_model.Field.DataType dataType = 2;</code>
   */
  public boolean hasDataType() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required .ai_sapper_walcdc_common_model.Field.DataType dataType = 2;</code>
   */
  public ai.sapper.walcdc.common.model.Field.DataType getDataType() {
    return dataType_;
  }

  private void initFields() {
    name_ = "";
    dataType_ = ai.sapper.walcdc.common.model.Field.DataType.BOOLEAN;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasDataType()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getNameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeEnum(2, dataType_.getNumber());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getNameBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, dataType_.getNumber());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static ai.sapper.walcdc.common.model.Field parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sapper.walcdc.common.model.Field parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.Field parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.sapper.walcdc.common.model.Field parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.Field parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ai.sapper.walcdc.common.model.Field parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.Field parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static ai.sapper.walcdc.common.model.Field parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static ai.sapper.walcdc.common.model.Field parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static ai.sapper.walcdc.common.model.Field parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(ai.sapper.walcdc.common.model.Field prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ai_sapper_walcdc_common_model.Field}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements ai.sapper.walcdc.common.model.FieldOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_Field_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_Field_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.sapper.walcdc.common.model.Field.class, ai.sapper.walcdc.common.model.Field.Builder.class);
    }

    // Construct using ai.sapper.walcdc.common.model.Field.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      dataType_ = ai.sapper.walcdc.common.model.Field.DataType.BOOLEAN;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.sapper.walcdc.common.model.WALCDC.internal_static_ai_sapper_walcdc_common_model_Field_descriptor;
    }

    public ai.sapper.walcdc.common.model.Field getDefaultInstanceForType() {
      return ai.sapper.walcdc.common.model.Field.getDefaultInstance();
    }

    public ai.sapper.walcdc.common.model.Field build() {
      ai.sapper.walcdc.common.model.Field result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ai.sapper.walcdc.common.model.Field buildPartial() {
      ai.sapper.walcdc.common.model.Field result = new ai.sapper.walcdc.common.model.Field(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.dataType_ = dataType_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.sapper.walcdc.common.model.Field) {
        return mergeFrom((ai.sapper.walcdc.common.model.Field)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.sapper.walcdc.common.model.Field other) {
      if (other == ai.sapper.walcdc.common.model.Field.getDefaultInstance()) return this;
      if (other.hasName()) {
        bitField0_ |= 0x00000001;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasDataType()) {
        setDataType(other.getDataType());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasName()) {
        
        return false;
      }
      if (!hasDataType()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.sapper.walcdc.common.model.Field parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.sapper.walcdc.common.model.Field) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required string name = 1;
    private java.lang.Object name_ = "";
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 1;</code>
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>required string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
      onChanged();
      return this;
    }

    // required .ai_sapper_walcdc_common_model.Field.DataType dataType = 2;
    private ai.sapper.walcdc.common.model.Field.DataType dataType_ = ai.sapper.walcdc.common.model.Field.DataType.BOOLEAN;
    /**
     * <code>required .ai_sapper_walcdc_common_model.Field.DataType dataType = 2;</code>
     */
    public boolean hasDataType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Field.DataType dataType = 2;</code>
     */
    public ai.sapper.walcdc.common.model.Field.DataType getDataType() {
      return dataType_;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Field.DataType dataType = 2;</code>
     */
    public Builder setDataType(ai.sapper.walcdc.common.model.Field.DataType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      dataType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required .ai_sapper_walcdc_common_model.Field.DataType dataType = 2;</code>
     */
    public Builder clearDataType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      dataType_ = ai.sapper.walcdc.common.model.Field.DataType.BOOLEAN;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:ai_sapper_walcdc_common_model.Field)
  }

  static {
    defaultInstance = new Field(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:ai_sapper_walcdc_common_model.Field)
}

