// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: walcdc.proto

package ai.sapper.walcdc.common.model;

public interface FieldValueOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required .ai_sapper_walcdc_common_model.Field field = 1;
  /**
   * <code>required .ai_sapper_walcdc_common_model.Field field = 1;</code>
   */
  boolean hasField();
  /**
   * <code>required .ai_sapper_walcdc_common_model.Field field = 1;</code>
   */
  ai.sapper.walcdc.common.model.Field getField();
  /**
   * <code>required .ai_sapper_walcdc_common_model.Field field = 1;</code>
   */
  ai.sapper.walcdc.common.model.FieldOrBuilder getFieldOrBuilder();

  // optional bytes value = 2;
  /**
   * <code>optional bytes value = 2;</code>
   */
  boolean hasValue();
  /**
   * <code>optional bytes value = 2;</code>
   */
  com.google.protobuf.ByteString getValue();
}
