// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: walcdc.proto

package ai.sapper.walcdc.common.model;

public interface FieldOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required string name = 1;
  /**
   * <code>required string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  // required .ai_sapper_walcdc_common_model.Field.DataType dataType = 2;
  /**
   * <code>required .ai_sapper_walcdc_common_model.Field.DataType dataType = 2;</code>
   */
  boolean hasDataType();
  /**
   * <code>required .ai_sapper_walcdc_common_model.Field.DataType dataType = 2;</code>
   */
  ai.sapper.walcdc.common.model.Field.DataType getDataType();
}
