// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: walcdc.proto

package ai.sapper.walcdc.common.model;

public interface TransactionOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required int64 txId = 1;
  /**
   * <code>required int64 txId = 1;</code>
   */
  boolean hasTxId();
  /**
   * <code>required int64 txId = 1;</code>
   */
  long getTxId();

  // repeated int64 timestamp = 2;
  /**
   * <code>repeated int64 timestamp = 2;</code>
   */
  java.util.List<java.lang.Long> getTimestampList();
  /**
   * <code>repeated int64 timestamp = 2;</code>
   */
  int getTimestampCount();
  /**
   * <code>repeated int64 timestamp = 2;</code>
   */
  long getTimestamp(int index);

  // required .ai_sapper_walcdc_common_model.Transaction.TxType type = 3;
  /**
   * <code>required .ai_sapper_walcdc_common_model.Transaction.TxType type = 3;</code>
   */
  boolean hasType();
  /**
   * <code>required .ai_sapper_walcdc_common_model.Transaction.TxType type = 3;</code>
   */
  ai.sapper.walcdc.common.model.Transaction.TxType getType();
}
