// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: walcdc.proto

package ai.sapper.walcdc.common.model;

public final class WALCDC {
  private WALCDC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_sapper_walcdc_common_model_Transaction_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_sapper_walcdc_common_model_Transaction_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_sapper_walcdc_common_model_Entity_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_sapper_walcdc_common_model_Entity_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_sapper_walcdc_common_model_Field_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_sapper_walcdc_common_model_Field_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_sapper_walcdc_common_model_FieldValue_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_sapper_walcdc_common_model_FieldValue_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_sapper_walcdc_common_model_DDLFieldChange_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_sapper_walcdc_common_model_DDLFieldChange_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_sapper_walcdc_common_model_DDLChangeSet_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_sapper_walcdc_common_model_DDLChangeSet_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_sapper_walcdc_common_model_DataFieldChange_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_sapper_walcdc_common_model_DataFieldChange_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_ai_sapper_walcdc_common_model_ChangeSet_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ai_sapper_walcdc_common_model_ChangeSet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014walcdc.proto\022\035ai_sapper_walcdc_common_" +
      "model\"\202\002\n\013Transaction\022\014\n\004txId\030\001 \002(\003\022\021\n\tt" +
      "imestamp\030\002 \003(\003\022?\n\004type\030\003 \002(\01621.ai_sapper" +
      "_walcdc_common_model.Transaction.TxType\"" +
      "\220\001\n\006TxType\022\025\n\021DDL_CREATE_ENTITY\020\000\022\025\n\021DDL" +
      "_UPDATE_ENTITY\020\001\022\023\n\017DDL_DROP_ENTITY\020\002\022\025\n" +
      "\021DML_INSERT_ENTITY\020\003\022\025\n\021DML_UPDATE_ENTIT" +
      "Y\020\004\022\025\n\021DML_DELETE_ENTITY\020\005\"M\n\006Entity\022\n\n\002" +
      "id\030\001 \002(\t\022\021\n\tnamespace\030\002 \002(\t\022\014\n\004name\030\003 \002(" +
      "\t\022\026\n\016schemaLocation\030\004 \001(\t\"\350\001\n\005Field\022\014\n\004n",
      "ame\030\001 \002(\t\022?\n\010dataType\030\002 \002(\0162-.ai_sapper_" +
      "walcdc_common_model.Field.DataType\"\217\001\n\010D" +
      "ataType\022\013\n\007BOOLEAN\020\000\022\t\n\005SHORT\020\001\022\007\n\003INT\020\002" +
      "\022\010\n\004LONG\020\003\022\t\n\005FLOAT\020\004\022\n\n\006DOUBLE\020\005\022\010\n\004BYT" +
      "E\020\006\022\010\n\004CHAR\020\007\022\n\n\006STRING\020\010\022\t\n\005ARRAY\020\t\022\n\n\006" +
      "OBJECT\020\n\022\n\n\006CUSTOM\020\013\"P\n\nFieldValue\0223\n\005fi" +
      "eld\030\001 \002(\0132$.ai_sapper_walcdc_common_mode" +
      "l.Field\022\r\n\005value\030\002 \001(\014\"~\n\016DDLFieldChange" +
      "\0226\n\010original\030\001 \001(\0132$.ai_sapper_walcdc_co" +
      "mmon_model.Field\0224\n\006target\030\002 \001(\0132$.ai_sa",
      "pper_walcdc_common_model.Field\"\276\001\n\014DDLCh" +
      "angeSet\0227\n\003tnx\030\001 \002(\0132*.ai_sapper_walcdc_" +
      "common_model.Transaction\0225\n\006entity\030\002 \002(\013" +
      "2%.ai_sapper_walcdc_common_model.Entity\022" +
      ">\n\007changes\030\003 \003(\0132-.ai_sapper_walcdc_comm" +
      "on_model.DDLFieldChange\"\370\001\n\017DataFieldCha" +
      "nge\0228\n\005value\030\001 \002(\0132).ai_sapper_walcdc_co" +
      "mmon_model.FieldValue\022C\n\002op\030\002 \003(\01627.ai_s" +
      "apper_walcdc_common_model.DataFieldChang" +
      "e.ChangeOp\022;\n\010original\030\003 \001(\0132).ai_sapper",
      "_walcdc_common_model.FieldValue\")\n\010Chang" +
      "eOp\022\007\n\003ADD\020\000\022\n\n\006RENAME\020\001\022\010\n\004DROP\020\002\"\274\001\n\tC" +
      "hangeSet\0227\n\003tnx\030\001 \002(\0132*.ai_sapper_walcdc" +
      "_common_model.Transaction\0225\n\006entity\030\002 \002(" +
      "\0132%.ai_sapper_walcdc_common_model.Entity" +
      "\022?\n\007changes\030\003 \003(\0132..ai_sapper_walcdc_com" +
      "mon_model.DataFieldChangeB)\n\035ai.sapper.w" +
      "alcdc.common.modelB\006WALCDCP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ai_sapper_walcdc_common_model_Transaction_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ai_sapper_walcdc_common_model_Transaction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ai_sapper_walcdc_common_model_Transaction_descriptor,
              new java.lang.String[] { "TxId", "Timestamp", "Type", });
          internal_static_ai_sapper_walcdc_common_model_Entity_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ai_sapper_walcdc_common_model_Entity_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ai_sapper_walcdc_common_model_Entity_descriptor,
              new java.lang.String[] { "Id", "Namespace", "Name", "SchemaLocation", });
          internal_static_ai_sapper_walcdc_common_model_Field_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_ai_sapper_walcdc_common_model_Field_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ai_sapper_walcdc_common_model_Field_descriptor,
              new java.lang.String[] { "Name", "DataType", });
          internal_static_ai_sapper_walcdc_common_model_FieldValue_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_ai_sapper_walcdc_common_model_FieldValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ai_sapper_walcdc_common_model_FieldValue_descriptor,
              new java.lang.String[] { "Field", "Value", });
          internal_static_ai_sapper_walcdc_common_model_DDLFieldChange_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_ai_sapper_walcdc_common_model_DDLFieldChange_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ai_sapper_walcdc_common_model_DDLFieldChange_descriptor,
              new java.lang.String[] { "Original", "Target", });
          internal_static_ai_sapper_walcdc_common_model_DDLChangeSet_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_ai_sapper_walcdc_common_model_DDLChangeSet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ai_sapper_walcdc_common_model_DDLChangeSet_descriptor,
              new java.lang.String[] { "Tnx", "Entity", "Changes", });
          internal_static_ai_sapper_walcdc_common_model_DataFieldChange_descriptor =
            getDescriptor().getMessageTypes().get(6);
          internal_static_ai_sapper_walcdc_common_model_DataFieldChange_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ai_sapper_walcdc_common_model_DataFieldChange_descriptor,
              new java.lang.String[] { "Value", "Op", "Original", });
          internal_static_ai_sapper_walcdc_common_model_ChangeSet_descriptor =
            getDescriptor().getMessageTypes().get(7);
          internal_static_ai_sapper_walcdc_common_model_ChangeSet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ai_sapper_walcdc_common_model_ChangeSet_descriptor,
              new java.lang.String[] { "Tnx", "Entity", "Changes", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
